// <auto-generated />
using System;
using Khodgard.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Khodgard.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Khodgard.Models.Exchange", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("ApiKey")
                        .HasColumnType("longtext");

                    b.Property<bool>("Enabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Secret")
                        .HasColumnType("longtext");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Exchange");

                    b.HasDiscriminator<string>("Type").HasValue("Exchange");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Khodgard.Models.Line", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<double>("Amount")
                        .HasColumnType("double");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("MapId")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(65,30)");

                    b.Property<byte>("Side")
                        .HasColumnType("tinyint unsigned");

                    b.Property<DateTime>("Updated")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("MapId");

                    b.ToTable("Line");
                });

            modelBuilder.Entity("Khodgard.Models.Map", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("ClearAgeDelay")
                        .HasColumnType("int");

                    b.Property<int>("ClearCountDelay")
                        .HasColumnType("int");

                    b.Property<int>("DepthLimit")
                        .HasColumnType("int");

                    b.Property<bool>("Enabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsRunning")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("LockedClearAge")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("LockedClearCount")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("LockedSync")
                        .HasColumnType("tinyint(1)");

                    b.Property<byte>("MapType")
                        .HasColumnType("tinyint unsigned");

                    b.Property<int>("MaxAge")
                        .HasColumnType("int");

                    b.Property<int>("MaxDeleteLines")
                        .HasColumnType("int");

                    b.Property<int>("MaxLines")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<double>("Ratio")
                        .HasColumnType("double");

                    b.Property<int>("SourceId")
                        .HasColumnType("int");

                    b.Property<int>("SyncDelay")
                        .HasColumnType("int");

                    b.Property<int>("SyncMultifold")
                        .HasColumnType("int");

                    b.Property<int>("SyncSegments")
                        .HasColumnType("int");

                    b.Property<int>("TargetId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SourceId");

                    b.HasIndex("TargetId");

                    b.ToTable("Map");
                });

            modelBuilder.Entity("Khodgard.Models.Market", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("AmountPrecision")
                        .HasColumnType("int");

                    b.Property<string>("BaseUnit")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("Enabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("ExchangeId")
                        .HasColumnType("int");

                    b.Property<decimal>("MaxPrice")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("MinPrice")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("PricePrecision")
                        .HasColumnType("int");

                    b.Property<string>("QuoteUnit")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("ExchangeId");

                    b.ToTable("Market");
                });

            modelBuilder.Entity("Khodgard.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<double>("Amount")
                        .HasColumnType("double");

                    b.Property<bool>("Enabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("LineId")
                        .HasColumnType("int");

                    b.Property<int>("MarketId")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(65,30)");

                    b.Property<byte>("Side")
                        .HasColumnType("tinyint unsigned");

                    b.Property<int>("Uid")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("LineId");

                    b.HasIndex("MarketId");

                    b.ToTable("Order");
                });

            modelBuilder.Entity("Khodgard.Exchanges.Bankdex.BankdexExchange", b =>
                {
                    b.HasBaseType("Khodgard.Models.Exchange");

                    b.HasDiscriminator().HasValue("Bankdex");
                });

            modelBuilder.Entity("Khodgard.Exchanges.Binance.BinanceExchange", b =>
                {
                    b.HasBaseType("Khodgard.Models.Exchange");

                    b.HasDiscriminator().HasValue("Binance");
                });

            modelBuilder.Entity("Khodgard.Models.Line", b =>
                {
                    b.HasOne("Khodgard.Models.Map", "Map")
                        .WithMany()
                        .HasForeignKey("MapId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Map");
                });

            modelBuilder.Entity("Khodgard.Models.Map", b =>
                {
                    b.HasOne("Khodgard.Models.Market", "Source")
                        .WithMany()
                        .HasForeignKey("SourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Khodgard.Models.Market", "Target")
                        .WithMany()
                        .HasForeignKey("TargetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Source");

                    b.Navigation("Target");
                });

            modelBuilder.Entity("Khodgard.Models.Market", b =>
                {
                    b.HasOne("Khodgard.Models.Exchange", "Exchange")
                        .WithMany()
                        .HasForeignKey("ExchangeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Exchange");
                });

            modelBuilder.Entity("Khodgard.Models.Order", b =>
                {
                    b.HasOne("Khodgard.Models.Line", "Line")
                        .WithMany()
                        .HasForeignKey("LineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Khodgard.Models.Market", "Market")
                        .WithMany()
                        .HasForeignKey("MarketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Line");

                    b.Navigation("Market");
                });
#pragma warning restore 612, 618
        }
    }
}
